// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BillingAttachmentType.
const (
	Applicationpdf BillingAttachmentType = "application/pdf"
	Imagejpeg      BillingAttachmentType = "image/jpeg"
	Imagepng       BillingAttachmentType = "image/png"
)

// Valid indicates whether the value is a known member of the BillingAttachmentType enum.
func (e BillingAttachmentType) Valid() bool {
	switch e {
	case Applicationpdf:
		return true
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	default:
		return false
	}
}

// Defines values for BillingCommandOperation.
const (
	Delete    BillingCommandOperation = "delete"
	Import    BillingCommandOperation = "import"
	Project   BillingCommandOperation = "project"
	Restore   BillingCommandOperation = "restore"
	Save      BillingCommandOperation = "save"
	Status    BillingCommandOperation = "status"
	Warehouse BillingCommandOperation = "warehouse"
)

// Valid indicates whether the value is a known member of the BillingCommandOperation enum.
func (e BillingCommandOperation) Valid() bool {
	switch e {
	case Delete:
		return true
	case Import:
		return true
	case Project:
		return true
	case Restore:
		return true
	case Save:
		return true
	case Status:
		return true
	case Warehouse:
		return true
	default:
		return false
	}
}

// Defines values for BillingDraftCreditMode.
const (
	Cash    BillingDraftCreditMode = "cash"
	Days    BillingDraftCreditMode = "days"
	Undated BillingDraftCreditMode = "undated"
)

// Valid indicates whether the value is a known member of the BillingDraftCreditMode enum.
func (e BillingDraftCreditMode) Valid() bool {
	switch e {
	case Cash:
		return true
	case Days:
		return true
	case Undated:
		return true
	default:
		return false
	}
}

// Defines values for BillingDraftPriceMode.
const (
	Exclusive BillingDraftPriceMode = "exclusive"
	Inclusive BillingDraftPriceMode = "inclusive"
)

// Valid indicates whether the value is a known member of the BillingDraftPriceMode enum.
func (e BillingDraftPriceMode) Valid() bool {
	switch e {
	case Exclusive:
		return true
	case Inclusive:
		return true
	default:
		return false
	}
}

// Defines values for BillingRecordKind.
const (
	Billing      BillingRecordKind = "billing"
	Consolidated BillingRecordKind = "consolidated"
)

// Valid indicates whether the value is a known member of the BillingRecordKind enum.
func (e BillingRecordKind) Valid() bool {
	switch e {
	case Billing:
		return true
	case Consolidated:
		return true
	default:
		return false
	}
}

// Defines values for BillingStatus.
const (
	Billed    BillingStatus = "billed"
	Cancelled BillingStatus = "cancelled"
	Draft     BillingStatus = "draft"
	Waiting   BillingStatus = "waiting"
)

// Valid indicates whether the value is a known member of the BillingStatus enum.
func (e BillingStatus) Valid() bool {
	switch e {
	case Billed:
		return true
	case Cancelled:
		return true
	case Draft:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Defines values for BillingWarehousePurpose.
const (
	Empty BillingWarehousePurpose = "ซื้อและขาย"
	N1    BillingWarehousePurpose = "ซื้อสินค้า"
	N2    BillingWarehousePurpose = "ขายสินค้า"
)

// Valid indicates whether the value is a known member of the BillingWarehousePurpose enum.
func (e BillingWarehousePurpose) Valid() bool {
	switch e {
	case Empty:
		return true
	case N1:
		return true
	case N2:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// BillingAttachment defines model for BillingAttachment.
type BillingAttachment struct {
	DataUrl string                `json:"dataUrl"`
	Id      string                `json:"id"`
	Name    string                `json:"name"`
	Size    int                   `json:"size"`
	Type    BillingAttachmentType `json:"type"`
}

// BillingAttachmentType defines model for BillingAttachment.Type.
type BillingAttachmentType string

// BillingCommand defines model for BillingCommand.
type BillingCommand struct {
	Draft     *BillingDraft           `json:"draft,omitempty"`
	Id        *string                 `json:"id,omitempty"`
	Operation BillingCommandOperation `json:"operation"`
	Project   *BillingProject         `json:"project,omitempty"`
	Record    *BillingRecord          `json:"record,omitempty"`
	Status    *BillingStatus          `json:"status,omitempty"`
	Version   *int64                  `json:"version,omitempty"`
	Warehouse *BillingWarehouse       `json:"warehouse,omitempty"`
}

// BillingCommandOperation defines model for BillingCommand.Operation.
type BillingCommandOperation string

// BillingCustomer defines model for BillingCustomer.
type BillingCustomer struct {
	Address    string `json:"address"`
	Branch     string `json:"branch"`
	Name       string `json:"name"`
	PostalCode string `json:"postalCode"`
	TaxId      string `json:"taxId"`
}

// BillingDraft defines model for BillingDraft.
type BillingDraft struct {
	Attachments      []BillingAttachment    `json:"attachments"`
	CreditDays       int                    `json:"creditDays"`
	CreditMode       BillingDraftCreditMode `json:"creditMode"`
	Customer         BillingCustomer        `json:"customer"`
	Date             string                 `json:"date"`
	Description      string                 `json:"description"`
	DocumentDiscount float64                `json:"documentDiscount"`
	DueDate          string                 `json:"dueDate"`
	InternalNote     string                 `json:"internalNote"`
	Items            []BillingLine          `json:"items"`
	Note             string                 `json:"note"`
	PriceMode        BillingDraftPriceMode  `json:"priceMode"`
	Project          string                 `json:"project"`
	Reference        string                 `json:"reference"`
	Salesperson      string                 `json:"salesperson"`
	SignatureEnabled bool                   `json:"signatureEnabled"`
	Warehouse        string                 `json:"warehouse"`
}

// BillingDraftCreditMode defines model for BillingDraft.CreditMode.
type BillingDraftCreditMode string

// BillingDraftPriceMode defines model for BillingDraft.PriceMode.
type BillingDraftPriceMode string

// BillingLine defines model for BillingLine.
type BillingLine struct {
	Description     string  `json:"description"`
	DiscountPercent float64 `json:"discountPercent"`
	Id              string  `json:"id"`
	Quantity        float64 `json:"quantity"`
	Unit            string  `json:"unit"`
	UnitPrice       float64 `json:"unitPrice"`
	VatRate         float64 `json:"vatRate"`
	WithholdingRate float64 `json:"withholdingRate"`
}

// BillingProject defines model for BillingProject.
type BillingProject struct {
	Customer string `json:"customer"`
	Id       string `json:"id"`
	Name     string `json:"name"`
}

// BillingRecord defines model for BillingRecord.
type BillingRecord struct {
	DeletedAt *string           `json:"deletedAt"`
	Draft     BillingDraft      `json:"draft"`
	Id        string            `json:"id"`
	Kind      BillingRecordKind `json:"kind"`
	Number    string            `json:"number"`
	Status    BillingStatus     `json:"status"`
	UpdatedAt string            `json:"updatedAt"`
	Version   int64             `json:"version"`
}

// BillingRecordKind defines model for BillingRecord.Kind.
type BillingRecordKind string

// BillingResult defines model for BillingResult.
type BillingResult struct {
	Project   *BillingProject   `json:"project,omitempty"`
	Record    *BillingRecord    `json:"record,omitempty"`
	Warehouse *BillingWarehouse `json:"warehouse,omitempty"`
}

// BillingStatus defines model for BillingStatus.
type BillingStatus string

// BillingWarehouse defines model for BillingWarehouse.
type BillingWarehouse struct {
	Address    string                  `json:"address"`
	Code       string                  `json:"code"`
	Contact    string                  `json:"contact"`
	Email      string                  `json:"email"`
	Id         string                  `json:"id"`
	Name       string                  `json:"name"`
	Phone      string                  `json:"phone"`
	PostalCode string                  `json:"postalCode"`
	Purpose    BillingWarehousePurpose `json:"purpose"`
}

// BillingWarehousePurpose defines model for BillingWarehouse.Purpose.
type BillingWarehousePurpose string

// BillingWorkspace defines model for BillingWorkspace.
type BillingWorkspace struct {
	Projects   []BillingProject   `json:"projects"`
	Records    []BillingRecord    `json:"records"`
	Warehouses []BillingWarehouse `json:"warehouses"`
}

// Error defines model for Error.
type Error struct {
	Code      string                 `json:"code"`
	Details   map[string]interface{} `json:"details"`
	Message   string                 `json:"message"`
	RequestId openapi_types.UUID     `json:"requestId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Failure defines model for Failure.
type Failure = ErrorResponse

// HealthResult defines model for HealthResult.
type HealthResult = Health

// MutateBillingJSONRequestBody defines body for MutateBilling for application/json ContentType.
type MutateBillingJSONRequestBody = BillingCommand

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetBilling Read billing documents, projects and warehouses
	// (GET /api/v1/billing)
	GetBilling(w http.ResponseWriter, r *http.Request)
	// MutateBilling Apply one atomic billing command. Editing requires the version last read; stale writes return 409. Import preserves local IDs and is idempotent.
	// (POST /api/v1/billing)
	MutateBilling(w http.ResponseWriter, r *http.Request)
	// GetLiveness Check whether the HTTP process is alive
	// (GET /health/live)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// GetReadiness Check whether PostgreSQL is reachable within the readiness deadline
	// (GET /health/ready)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetBilling Read billing documents, projects and warehouses
// (GET /api/v1/billing)
func (_ Unimplemented) GetBilling(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// MutateBilling Apply one atomic billing command. Editing requires the version last read; stale writes return 409. Import preserves local IDs and is idempotent.
// (POST /api/v1/billing)
func (_ Unimplemented) MutateBilling(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetLiveness Check whether the HTTP process is alive
// (GET /health/live)
func (_ Unimplemented) GetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Check whether PostgreSQL is reachable within the readiness deadline
// (GET /health/ready)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBilling operation middleware
func (siw *ServerInterfaceWrapper) GetBilling(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBilling(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MutateBilling operation middleware
func (siw *ServerInterfaceWrapper) MutateBilling(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MutateBilling(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health/live", wrapper.GetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health/ready", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/billing", wrapper.GetBilling)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/billing", wrapper.MutateBilling)
	})

	return r
}
