import { expect, test } from '@playwright/test'

test('credit modes and editable due dates persist and print correctly', async ({ page }) => {
  await page.goto('/sales/quotations/new')
  await expect(page.getByRole('button', { name: 'บันทึกเอกสาร', exact: true })).toBeEnabled()
  await page.getByLabel('ชื่อลูกค้า', { exact: false }).fill('ทดสอบเครดิต')
  await page.getByLabel('ชื่อสินค้า รายการที่ 1', { exact: true }).fill('บริการทดสอบ')
  await page.getByLabel(/^วันที่/).fill('2026-09-13')
  await page.getByLabel('เครดิต (วัน)', { exact: true }).fill('17')
  await expect(page.getByLabel('ครบกำหนด', { exact: true })).toHaveValue('2026-09-30')
  await page.getByLabel('ครบกำหนด', { exact: true }).fill('2026-10-03')
  await expect(page.getByLabel('เครดิต (วัน)', { exact: true })).toHaveValue('20')
  await page.getByRole('button', { name: 'เลือกประเภทเครดิต', exact: true }).click()
  await page.getByRole('button', { name: 'เงินสด', exact: true }).click()
  await expect(page.getByLabel('ครบกำหนด', { exact: true })).toHaveCount(0)
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.print-document')).toContainText('เงินสด')
  await expect(page.locator('.print-document')).not.toContainText('ครบกำหนด')
  await page.emulateMedia({ media: 'screen' })
  await page.getByRole('button', { name: 'เลือกประเภทเครดิต', exact: true }).click()
  await page.getByRole('button', { name: 'เครดิต (ไม่แสดงวันที่)', exact: true }).click()
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.print-document')).toContainText('เครดิต (ไม่แสดงวันที่)')
  await expect(page.locator('.print-document')).not.toContainText('ครบกำหนด')
  await page.emulateMedia({ media: 'screen' })
  await page.getByRole('button', { name: 'บันทึกเอกสาร', exact: true }).click()
  await page.getByRole('searchbox', { name: 'ค้นหาใบเสนอราคา', exact: true }).fill('ทดสอบเครดิต')
  await page.locator('tbody tr').filter({ hasText: 'ทดสอบเครดิต' }).locator('a.document-link').click()
  await expect(page.getByText('เครดิต (ไม่แสดงวันที่)', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'เลือกประเภทเครดิต', exact: true }).click()
  await page.getByRole('button', { name: 'เครดิต (วัน)', exact: true }).click()
  await page.getByLabel('ครบกำหนด', { exact: true }).fill('2026-11-01')
  await page.getByRole('button', { name: 'บันทึกเอกสาร', exact: true }).click()
  await page.getByRole('searchbox', { name: 'ค้นหาใบเสนอราคา', exact: true }).fill('ทดสอบเครดิต')
  await page.locator('tbody tr').filter({ hasText: 'ทดสอบเครดิต' }).locator('a.document-link').click()
  await expect(page.getByLabel('ครบกำหนด', { exact: true })).toHaveValue('2026-11-01')
  await page.reload()
  await expect(page.getByLabel('ครบกำหนด', { exact: true })).toHaveValue('2026-11-01')
  await expect(page.getByLabel('เครดิต (วัน)', { exact: true })).toHaveValue('49')
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.print-document')).toContainText('ครบกำหนด 1 พ.ย. 2026')
})
