import { expect, test } from '@playwright/test'

test('create, calculate, save, reload, find and edit a quotation', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/sales/quotations')
  await expect(page.getByRole('heading', { name: 'ใบเสนอราคา', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'สร้างใหม่', exact: true }).click()
  await page.getByRole('button', { name: 'บันทึกเอกสาร', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('กรุณาระบุชื่อลูกค้า')
  await page.getByLabel('ชื่อลูกค้า', { exact: false }).fill('บริษัท ทดสอบระบบ จำกัด')
  await page.getByLabel('ชื่อสินค้า รายการที่ 1', { exact: true }).fill('บริการออกแบบทดสอบ')
  await page.getByLabel('จำนวน รายการที่ 1', { exact: true }).fill('2')
  await page.getByLabel('ราคาต่อหน่วย รายการที่ 1', { exact: true }).fill('1000')
  await page.getByLabel('ส่วนลด รายการที่ 1', { exact: true }).fill('10')
  await page.getByLabel('หัก ณ ที่จ่าย รายการที่ 1', { exact: true }).selectOption('3')
  await page.getByLabel('ส่วนลดเพิ่มเติม (บาท)', { exact: true }).fill('100')
  await expect(page.getByTestId('grand-total')).toHaveText('1,819.00')
  await expect(page.getByTestId('payable-total')).toHaveText('1,768.00')
  await page.getByRole('button', { name: 'เพิ่มแถวรายการ' }).click()
  await expect(page.getByLabel('ชื่อสินค้า รายการที่ 2')).toBeVisible()
  await page.getByRole('button', { name: 'ลบรายการที่ 2' }).click()
  await page.getByLabel('โน้ตภายในบริษัท', { exact: true }).fill('INTERNAL-NOT-PRINTED')
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.print-document')).toBeVisible()
  await expect(page.locator('.print-document')).not.toContainText('INTERNAL-NOT-PRINTED')
  await page.emulateMedia({ media: 'screen' })
  await page.getByRole('button', { name: 'บันทึกเอกสาร', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('บันทึกใบเสนอราคาเรียบร้อยแล้ว')
  await page.reload()
  await page.getByRole('searchbox', { name: 'ค้นหาใบเสนอราคา', exact: true }).fill('บริษัท ทดสอบระบบ จำกัด')
  const row = page.locator('tbody tr').filter({ hasText: 'บริษัท ทดสอบระบบ จำกัด' })
  await expect(row).toHaveCount(1)
  await expect(row).toContainText('1,819.00')
  await row.locator('a.document-link').click()
  await expect(page.getByLabel('ชื่อลูกค้า', { exact: false })).toHaveValue('บริษัท ทดสอบระบบ จำกัด')
  await page.getByLabel('รายละเอียด', { exact: true }).fill('แก้ไขแล้ว')
  await page.getByRole('button', { name: 'บันทึกเอกสาร', exact: true }).click()
  await page.getByRole('searchbox', { name: 'ค้นหาใบเสนอราคา', exact: true }).fill('ไม่มีข้อมูลนี้')
  await expect(page.getByText('ไม่พบใบเสนอราคา', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('mobile navigation and document form do not overflow the page', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/sales/quotations')
  await expect(page.getByRole('navigation', { name: 'เอกสารการขาย' })).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'เปิดเมนูเอกสารการขาย' }).click()
  await expect(page.getByRole('navigation', { name: 'เอกสารการขาย' })).toBeVisible()
  await page.getByRole('button', { name: 'ปิดเมนู', exact: true }).click({ position: { x: 350, y: 500 } })
  await page.getByRole('link', { name: 'สร้างใหม่', exact: true }).click()
  await expect(page.getByLabel('ชื่อลูกค้า', { exact: false })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
