import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('selection downloads a real PDF and prints only selected documents or envelopes', async ({ page }) => {
  await page.addInitScript(() => { window.print = () => { document.documentElement.dataset.printed = 'yes' } })
  await page.goto('/sales/quotations')
  await page.getByRole('checkbox', { name: 'เลือก QT202609130001', exact: true }).check()
  await page.getByRole('checkbox', { name: 'เลือก QT202609120001', exact: true }).check()
  await expect(page.getByText('เลือก 2 รายการ', { exact: true })).toBeVisible()
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'ดาวน์โหลด PDF ที่เลือก', exact: true }).click()
  const pdf = await downloaded
  expect(pdf.suggestedFilename()).toBe('quotations.pdf')
  const path = await pdf.path()
  expect(path).toBeTruthy()
  const data = await readFile(path!)
  expect(data.subarray(0, 5).toString()).toBe('%PDF-')
  expect(data.length).toBeGreaterThan(10000)
  await pdf.saveAs('_wrx-output/evidence/quotations-selected.pdf')
  await page.getByRole('button', { name: 'พิมพ์เอกสารที่เลือก', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-printed', 'yes')
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.print-batch .print-document')).toHaveCount(2)
  await expect(page.locator('.print-batch')).toContainText('QT202609130001')
  await expect(page.locator('.print-batch')).not.toContainText('QT202609110001')
  await expect(page.locator('.screen-document')).not.toBeVisible()
  const printedDocuments = await page.pdf({ preferCSSPageSize: true })
  expect(printedDocuments.toString('latin1').match(/\/Type\s*\/Page\b/g)).toHaveLength(2)
  await page.emulateMedia({ media: 'screen' })
  await page.getByRole('button', { name: 'พิมพ์จ่าหน้าซองที่เลือก', exact: true }).click()
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.envelope-sheet')).toHaveCount(2)
  await expect(page.locator('.envelope-sheet').first()).toContainText('บริษัท บลูสกาย สตูดิโอ จำกัด')
  const envelopes = await page.pdf({ path: '_wrx-output/evidence/quotations-envelopes.pdf', preferCSSPageSize: true })
  expect(envelopes.toString('latin1').match(/\/Type\s*\/Page\b/g)).toHaveLength(2)
  await page.emulateMedia({ media: 'screen' })
  await page.getByRole('button', { name: 'ยกเลิกการเลือกทั้งหมด' }).click()
  await expect(page.getByRole('button', { name: 'ดาวน์โหลด PDF ที่เลือก', exact: true })).toHaveCount(0)
})

test('row status, share, duplicate and confirmed delete work with saved data', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/sales/quotations')
  await page.getByRole('button', { name: 'เปลี่ยนสถานะ QT202609130001', exact: true }).click()
  await page.getByRole('button', { name: 'อนุมัติ', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('เปลี่ยนสถานะ')
  await page.reload()
  const status = page.getByRole('button', { name: 'เปลี่ยนสถานะ QT202609130001', exact: true })
  await expect(status).toContainText('อนุมัติแล้ว')
  await status.click()
  await page.getByRole('button', { name: 'ไม่อนุมัติ', exact: true }).click()
  await expect(status).toContainText('ไม่อนุมัติ')
  await page.getByRole('button', { name: 'จัดการ QT202609130001', exact: true }).click()
  await page.getByRole('button', { name: 'แชร์', exact: true }).click()
  const share = page.getByRole('dialog')
  await expect(share).toContainText('แชร์ใบเสนอราคา QT202609130001')
  await expect(share.getByRole('button', { name: 'ดาวน์โหลด PDF เพื่อส่งต่อ' })).toBeEnabled()
  await share.getByRole('button', { name: 'ปิด', exact: true }).click()
  await page.getByRole('button', { name: 'จัดการ QT202609130001', exact: true }).click()
  await page.getByRole('button', { name: 'สร้างซ้ำ', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'แก้ไขใบเสนอราคา', exact: true })).toBeVisible()
  await expect(page.getByText('QT202609130002', { exact: true }).first()).toBeVisible()
  await page.getByRole('link', { name: 'ปิดหน้าต่าง', exact: true }).click()
  await page.getByRole('button', { name: 'จัดการ QT202609130002', exact: true }).click()
  await page.getByRole('button', { name: 'ลบ', exact: true }).click()
  await page.getByRole('button', { name: 'ยกเลิก', exact: true }).click()
  await expect(page.getByRole('button', { name: 'จัดการ QT202609130002', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'จัดการ QT202609130002', exact: true }).click()
  await page.getByRole('button', { name: 'ลบ', exact: true }).click()
  await page.getByRole('button', { name: 'ยืนยันลบ', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'จัดการ QT202609130002', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('button', { name: 'จัดการ QT202609130002', exact: true })).toHaveCount(0)
  expect(errors).toEqual([])
})

test('all seven sales menus open and highlight their own page', async ({ page }) => {
  await page.goto('/sales/quotations')
  const menu = page.getByRole('navigation', { name: 'เอกสารการขาย', exact: true })
  await expect(menu.getByRole('link')).toHaveCount(7)
  for (const label of ['ใบวางบิล', 'ใบกำกับภาษี', 'ใบเสร็จรับเงิน', 'ขายเงินสด', 'ใบลดหนี้', 'ใบเพิ่มหนี้', 'ใบเสนอราคา']) {
    await menu.getByRole('link', { name: label, exact: true }).click()
    await expect(page.getByRole('heading', { name: label, exact: true })).toBeVisible()
    await expect(menu.getByRole('link', { name: label, exact: true })).toHaveAttribute('aria-current', 'page')
  }
})
